plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.erik.screenobserver'
    compileSdk 36

    defaultConfig {
        applicationId 'com.erik.screenobserver'
        minSdk 26
        targetSdk 36
        versionCode 11
        versionName '2.4.0'
    }

    kotlinOptions {
        jvmTarget = '21'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
    implementation 'com.google.ai.edge.litertlm:litertlm-android:0.14.0'
}
