plugins { id 'com.android.application' }

android {
    namespace 'com.erik.screenobserver'
    compileSdk 36

    defaultConfig {
        applicationId 'com.erik.screenobserver'
        minSdk 26
        targetSdk 36
        versionCode 9
        versionName '2.2.0'
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
